[project]
name = "fastapi-ecommerce"
version = "0.1.0"
description = "Simple FastAPI CRUD App"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "asyncpg>=0.30.0",
    "bcrypt==4.0.1",
    "fastapi>=0.117.1",
    "greenlet>=3.2.4",
    "isort>=6.0.1",
    "orjson>=3.11.3",
    "passlib>=1.7.4",
    "pydantic[email]>=2.11.9",
    "pydantic-settings>=2.10.1",
    "ruff>=0.13.1",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.36.0",
    "pyjwt>=2.10.1",
    "python-multipart>=0.0.20",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "types-passlib>=1.7.7.20250602",
]


[tool.ruff]
line-length = 120
indent-width = 4
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    ".venv",
    "migrations"
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C",   # flake8-comprehensions
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "ARG", # flake8-unused-arguments
    "ASYNC", # flake8-async
    "S",   # flake8-bandit (security)
    "TCH", # flake8-type-checking
    "RUF", # Ruff-specific rules
]

[tool.ruff.lint.isort]
known-first-party = ["app"]
known-third-party = ["fastapi", "pydantic", "loguru", "httpx"]
classes = ["dataclass", "enum", "exception", "model", "namedtuple", "class", "type"]
constants = ["constant", "final"]
variables = ["variable", "var"]
order-by-type = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.mypy]
exclude = [
    ".*/migrations",
]
